version: '3.7'

services:
  regression:
    image: python:3.7
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - ./:/usr/workspace
    cmmand: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
        - LOGIN=${LOGIN}
        - PASSWORD=${PASSWORD}