name: UI Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Allure history from gh-pages
        run: |
          mkdir -p allure-results/history
          git fetch origin gh-pages --depth=1
          git checkout origin/gh-pages -- Practice_orange/history || true
          cp -r Practice_orange/history allure-results/ || true

      - name: Run UI-tests via Docker Compose
        run: docker compose up --build --exit-code-from regression

      - name: Copy updated history
        run: |
          mkdir -p allure-report/history
          cp -r allure-results/history allure-report/ || true

      - name: Generate Allure report with history
        run: |
          docker compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-report/history

  deploy:
    name: Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Download Allure history
        uses: actions/download-artifact@v4
        with:
          name: allure-history
          path: allure-report/history

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_dir: allure-report