name: UI Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout gh-pages for Allure history
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Restore Allure history
        run: |
          mkdir -p allure-results/history allure-report/history
          cp history/history.json allure-results/history/ || true
          cp history/history.json allure-report/history/ || true

      - name: Ensure Allure history directory exists
        run: mkdir -p allure-results/history

      - name: Run UI-tests via Docker Compose
        run: docker compose up --build --exit-code-from regression

      - name: Generate Allure report with history
        run: |
          docker compose run regression /bin/sh -c "mkdir -p allure-results && allure generate allure-results --clean -o allure-report"
          cp -r allure-results/history allure-report/ || true

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-report/history

  deploy:
    name: Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout gh-pages for Allure history
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Restore Allure history before deployment
        run: |
          mkdir -p allure-report/history
          cp history/history.json allure-report/history/ || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_dir: allure-report
