name: UI Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Копируем ветку gh-pages (для хранения истории)
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Debug: Check gh-pages contents
        run: ls -la gh-pages

      # Копируем историю из gh-pages в allure-results
      - name: Restore Allure history
        run: |
          mkdir -p allure-results/history
          cp -r gh-pages/Practice_orange/history allure-results/ || true

      - name: Debug: Check restored history
        run: ls -la allure-results/history

      # Запускаем UI-тесты
      - name: Run UI-tests via Docker Compose
        run: docker compose up --build --exit-code-from regression

      # Подставляем историю в отчет перед генерацией
      - name: Copy updated history to report
        run: |
          mkdir -p allure-report/history
          cp -r allure-results/history/* allure-report/history/ || true

      - name: Debug: Check report history before generation
        run: ls -la allure-report/history

      # Генерируем Allure-отчет
      - name: Generate Allure report with history
        run: docker compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Debug: Check final report
        run: ls -la allure-report/history

      # Загружаем отчет и историю как артефакты
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-report/history

      # **Сохраняем обновленную историю обратно в gh-pages**
      - name: Save updated history to gh-pages
        run: |
          cp -r allure-report/history gh-pages/Practice_orange/
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Practice_orange/history
          git commit -m "Update Allure history [CI]" || echo "No changes to commit"
          git push origin gh-pages

  deploy:
    name: Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Debug: Check downloaded report
        run: ls -la allure-report

      - name: Download Allure history
        uses: actions/download-artifact@v4
        with:
          name: allure-history
          path: allure-report/history

      - name: Debug: Check downloaded history
        run: ls -la allure-report/history

      # Деплоим отчет в gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_dir: allure-report
