name: UI Tests

on: workflow_dispatch  # Триггер: запуск вручную

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout repository  # Клонирование кода репозитория
      uses: actions/checkout@v4

    - name: Download Allure history from gh-pages (if exists)
      run: |
        git fetch origin gh-pages --depth=1  # Загружаем только последний коммит gh-pages
        git checkout gh-pages -- allure-report/history || mkdir -p allure-results/history  # Если history есть, берем его, иначе создаем пустую папку

    - name: Debug Allure history  # Проверяем, существует ли папка history
      run: ls -lah allure-results/history || echo "No history found"

    - name: Run UI-tests via Docker Compose  # Запуск тестов через Docker Compose
      run: docker compose up --build --exit-code-from regression

    - name: Copy Allure history to results
      run: |
        mkdir -p allure-results/history  # Создаем папку для истории, если её нет
        cp -r allure-report/history allure-results/ || true  # Копируем историю в allure-results

    - name: Generate Allure report with history
      run: |
        docker compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"  # Генерация отчета с учетом истории

    - name: Upload Allure Report  # Загружаем сгенерированный отчет как артефакт
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

  deploy:
    name: Deploy to GitHub Pages  # Деплой отчета на GitHub Pages
    needs: test  # Выполняется только после успешного тестирования
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository  # Клонируем репозиторий
      uses: actions/checkout@v4

    - name: Download Allure Report  # Загружаем артефакт с отчетом
      uses: actions/download-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Copy history from previous reports
      run: |
        git fetch origin gh-pages --depth=1  # Загружаем последний коммит gh-pages
        git checkout gh-pages -- allure-report/history || mkdir -p allure-report/history  # Если history есть, копируем, иначе создаем пустую папку

    - name: Deploy to GitHub Pages  # Публикуем отчет на GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.CI_TOKEN }}  # Используем секретный токен для пуша в gh-pages
        publish_dir: allure-report  # Папка с отчетом
