name: UI Tests

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch Allure history from gh-pages
      run: |
        git fetch origin gh-pages --depth=1 || echo "No gh-pages branch yet"
        mkdir -p allure-results/history
        git checkout gh-pages -- allure-report/history || echo "No history folder found in gh-pages"
        sudo cp -R allure-report/history/* allure-results/history/ || echo "No previous history found"
        ls -la allure-results/history || echo "History not copied correctly"

    - name: Run UI-tests via Docker Compose
      run: docker compose up --build --exit-code-from regression

    - name: Generate Allure report with history
      run: |
        mkdir -p allure-report/history
        sudo cp -R allure-results/history/* allure-report/history/ || echo "No history to copy"
        docker compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Upload Allure history
      uses: actions/upload-artifact@v4
      with:
        name: allure-history
        path: allure-report/history

  deploy:
    name: Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Allure Report
      uses: actions/download-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Try to Download Allure history (if exists)
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: allure-history
        path: allure-report/history

    - name: Ensure Allure history directory exists
      run: mkdir -p allure-report/history

    - name: Commit and Push Allure history to gh-pages
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout gh-pages || git checkout -b gh-pages
        mkdir -p allure-report/history
        sudo cp -R allure-report/history allure-report/ || echo "No history to copy"
        git add allure-report/history || echo "Nothing to commit"
        git commit -m "Update Allure history" || echo "No changes to commit"
        git push origin gh-pages || echo "Push failed"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.CI_TOKEN }}
        publish_dir: allure-report
