name: UI Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run UI-tests via Docker Compose
      run: docker compose up --build --exit-code-from regression

    - name: Debug allure-results
      run: ls -la allure-results || echo "No allure-results directory"

    - name: Generate Allure report
      run: |
        mkdir -p allure-report/history
        if [ -d allure-results/history ]; then
          cp -r allure-results/history allure-report/
        else
          echo "No history to copy"
        fi
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

  deploy:
    name: Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Allure Report
      uses: actions/download-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    - name: Ensure gh-pages branch exists
      run: |
        git fetch origin gh-pages || git checkout --orphan gh-pages
        git checkout gh-pages

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.CI_TOKEN }}
        publish_dir: allure-report
