name: UI Tests

on:
  push:
    branches:
      - main  # Или используйте другую ветку, по которой будет запускаться workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker and docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo apt-get install -y docker-compose  # Устанавливаем docker-compose

    - name: Run UI-tests via docker-compose
      run: docker-compose up --exit-code-from regression

    - name: Generate Allure report
      run: sudo docker-compose run regression allure /bin/sh -c "allure generate allure-results --clean -o allure-report"

  deploy:
    name: Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: ./.github/workflows/deploy.yml
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
